### ISSUE TITLE
Build error when using [FromBodyAttribute] decorators in controller

### ISSUE THREAD

**Issue by unearthly85** [vitalybibikov/AzureExtensions.Swashbuckle#56]
To recreate this build error, I created a new Azure Functions V3 project in VS 2019.  Then decorated the premade endpoint with `[FromBody]`, built and verify that the endpoint works.

```
[FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] 
            [FromBody] MyTestRequest requestObject, HttpRequest req,
            ILogger log)
        {
            string responseMessage = "Hello. This HTTP triggered function executed successfully.";
            return new OkObjectResult(responseMessage);
        }
```

Add AzureExtensions.Swashbuckle from Nuget, and I get a new error when trying to build:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at MakeFunctionJson.AttributeExtensions.IsWebJobsAttribute(CustomAttribute attribute)
   at MakeFunctionJson.ParameterInfoExtensions.<>c.<ToFunctionJsonBindings>b__1_0(CustomAttribute a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.ParameterInfoExtensions.ToFunctionJsonBindings(ParameterDefinition parameterInfo)
   at MakeFunctionJson.MethodInfoExtensions.<>c.<ToFunctionJson>b__6_1(ParameterDefinition p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodDefinition method, String assemblyPath)
   at MakeFunctionJson.FunctionJsonConverter.GenerateFunctions(IEnumerable`1 types)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
   at MakeFunctionJson.FunctionJsonConverter.TryRun()
Error generating functions metadata
	TestFunctionV3	C:\Users\jclark2\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets	32	
```
Remove `[FromBody] MyTestRequest requestObject` from the endpoint, everything works again.

Seems to be there is a conflict

**Comment by billchesnut** [comment]
Any update on this, having the same issue?

**Comment by billchesnut** [comment]
got what I was trying to do, to work with [RequestBodyType(typeof(Sample), "sample")] Sample sample

**Comment by vitalybibikov** [comment]
Looks like the issue with the FuncApps => https://github.com/Azure/azure-functions-vs-build-sdk/issues/435

**Comment by vitalybibikov** [comment]
Closed as there is no activity

**Comment by HolisticDeveloper** [comment]
`[FromBody]` seems to be [unnecessary](https://stackoverflow.com/questions/59985215/azure-functions-3-and-frombody-modelbinding#comment117457903_59985444). Indeed, I was able to remove the attribute and still get my function to work as it did before.
